name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@3.6.0
        with:
          distribution: temurin
          java-version: 17
      - name: Build with Gradle
        run: gradle shadowJar
